const catchAsync = require("../errorHandler/catchAsync");
const AppError = require("../errorHandler/appError");
const User = require("../models/userModel");
// Protect middleware -> For access control of admin users
exports.protect = catchAsync(async (req, res, next) => {
  let token;
  // Checking the Authorization in headers .
  if (
    req.headers.authorization &&
    req.headers.authorization.startsWith("Bearer")
  ) {
    // Getting the provided token.
    token = req.headers.authorization.split(" ")[1];
  } else {
    // Handling header doesn't contain AuthorizationToken.
    next(new AppError("Authentication token not provided", 401));
    return;
  }

  // ? Verifying the token is generated by this our api.
  // console.log(token);
  const verified = await promisify(jwt.verify)(token, config.jwtSecret);
  // console.log("verified", verified.id);
  // passing the id to the next middleware
  res.locals.id = verified.id;
  // console.log("req.id", req.id);

  res.locals.role = verified.role;
  // console.log("req.role", req.role);

  next();
});

exports.isAdmin = catchAsync(async (req, res, next) => {
  const id = res.locals.id;
  // getting the user related to the current token.
  const admin = await User.findById(id);

  if (admin.role !== "admin") {
    // not authorized if user doesn't exist!
    next(new AppError("Not Authorized", 401));
    return;
  }

  res.locals.admin = admin;

  next();
});

// exports.loginTokenAdmin = catchAsync(async (req, res) => {
//   const id = res.locals.id;
//   // getting the user related to the current token.
//   const admin = await Admin.findById(id);
//   if (!admin) {
//     // not authorized if user doesn't exist!
//     next(new AppError("Not Authorized", 401));
//     return;
//   }

//   res.status(200).json(admin);
// });

// exports.loginTokenCustomer = catchAsync(async (req, res) => {
//   const id = res.locals.id;
//   // getting the user related to the current token.
//   const user = await Customer.findById(id);
//   if (!user) {
//     // not authorized if user doesn't exist!
//     next(new AppError("Not Authorized", 401));
//     return;
//   }

//

//   res.status(200).json(user);
// });
// exports.loginTokenOwner = catchAsync(async (req, res) => {
//   const id = res.locals.id;
//   // getting the user related to the current token.
//   const user = await Owner.findById(id);
//   if (!user) {
//     // not authorized if user doesn't exist!
//     next(new AppError("Not Authorized", 401));
//     return;
//   }

//

//   res.status(200).json(user);
// });
